/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 95
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 70
#define ALIAS_COUNT 1
#define TOKEN_COUNT 42
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 2
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym_source_token1 = 1,
  anon_sym_diff = 2,
  aux_sym_command_token1 = 3,
  anon_sym_new = 4,
  anon_sym_deleted = 5,
  anon_sym_file = 6,
  anon_sym_mode = 7,
  anon_sym_old = 8,
  anon_sym_rename = 9,
  anon_sym_from = 10,
  anon_sym_to = 11,
  anon_sym_Binary = 12,
  anon_sym_files = 13,
  anon_sym_and = 14,
  anon_sym_differ = 15,
  anon_sym_index = 16,
  anon_sym_DOT_DOT = 17,
  anon_sym_similarity = 18,
  anon_sym_index2 = 19,
  aux_sym_similarity_token1 = 20,
  anon_sym_PERCENT = 21,
  anon_sym_DASH_DASH_DASH = 22,
  anon_sym_PLUS_PLUS_PLUS = 23,
  anon_sym_AT_AT = 24,
  anon_sym_AT_AT2 = 25,
  aux_sym_location_token1 = 26,
  anon_sym_PLUS = 27,
  anon_sym_PLUS_PLUS = 28,
  anon_sym_PLUS_PLUS_PLUS_PLUS = 29,
  anon_sym_GT = 30,
  anon_sym_DASH = 31,
  anon_sym_DASH_DASH = 32,
  anon_sym_DASH_DASH_DASH_DASH = 33,
  anon_sym_LT = 34,
  anon_sym_BANG = 35,
  anon_sym_SPACE = 36,
  anon_sym_POUND = 37,
  anon_sym_BSLASH = 38,
  sym_linerange = 39,
  aux_sym_filename_token1 = 40,
  sym_commit = 41,
  sym_source = 42,
  sym__line = 43,
  sym_block = 44,
  sym_hunks = 45,
  sym_hunk = 46,
  sym_changes = 47,
  sym_command = 48,
  sym_file_change = 49,
  sym_binary_change = 50,
  sym_index = 51,
  sym_similarity = 52,
  sym_old_file = 53,
  sym_new_file = 54,
  sym_location = 55,
  sym_addition = 56,
  sym_deletion = 57,
  sym_change = 58,
  sym_context = 59,
  sym_comment = 60,
  sym_special = 61,
  sym_filename = 62,
  sym_mode = 63,
  aux_sym_source_repeat1 = 64,
  aux_sym_block_repeat1 = 65,
  aux_sym_hunks_repeat1 = 66,
  aux_sym_changes_repeat1 = 67,
  aux_sym_changes_repeat2 = 68,
  aux_sym_filename_repeat1 = 69,
  alias_sym_score = 70,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym_source_token1] = "source_token1",
  [anon_sym_diff] = "diff",
  [aux_sym_command_token1] = "argument",
  [anon_sym_new] = "new",
  [anon_sym_deleted] = "deleted",
  [anon_sym_file] = "file",
  [anon_sym_mode] = "mode",
  [anon_sym_old] = "old",
  [anon_sym_rename] = "rename",
  [anon_sym_from] = "from",
  [anon_sym_to] = "to",
  [anon_sym_Binary] = "Binary",
  [anon_sym_files] = "files",
  [anon_sym_and] = "and",
  [anon_sym_differ] = "differ",
  [anon_sym_index] = "index",
  [anon_sym_DOT_DOT] = "..",
  [anon_sym_similarity] = "similarity",
  [anon_sym_index2] = "index",
  [aux_sym_similarity_token1] = "similarity_token1",
  [anon_sym_PERCENT] = "%",
  [anon_sym_DASH_DASH_DASH] = "---",
  [anon_sym_PLUS_PLUS_PLUS] = "+++",
  [anon_sym_AT_AT] = "@@",
  [anon_sym_AT_AT2] = "@@",
  [aux_sym_location_token1] = "location_token1",
  [anon_sym_PLUS] = "+",
  [anon_sym_PLUS_PLUS] = "++",
  [anon_sym_PLUS_PLUS_PLUS_PLUS] = "++++",
  [anon_sym_GT] = ">",
  [anon_sym_DASH] = "-",
  [anon_sym_DASH_DASH] = "--",
  [anon_sym_DASH_DASH_DASH_DASH] = "----",
  [anon_sym_LT] = "<",
  [anon_sym_BANG] = "!",
  [anon_sym_SPACE] = " ",
  [anon_sym_POUND] = "#",
  [anon_sym_BSLASH] = "\\",
  [sym_linerange] = "linerange",
  [aux_sym_filename_token1] = "filename_token1",
  [sym_commit] = "commit",
  [sym_source] = "source",
  [sym__line] = "_line",
  [sym_block] = "block",
  [sym_hunks] = "hunks",
  [sym_hunk] = "hunk",
  [sym_changes] = "changes",
  [sym_command] = "command",
  [sym_file_change] = "file_change",
  [sym_binary_change] = "binary_change",
  [sym_index] = "index",
  [sym_similarity] = "similarity",
  [sym_old_file] = "old_file",
  [sym_new_file] = "new_file",
  [sym_location] = "location",
  [sym_addition] = "addition",
  [sym_deletion] = "deletion",
  [sym_change] = "change",
  [sym_context] = "context",
  [sym_comment] = "comment",
  [sym_special] = "special",
  [sym_filename] = "filename",
  [sym_mode] = "mode",
  [aux_sym_source_repeat1] = "source_repeat1",
  [aux_sym_block_repeat1] = "block_repeat1",
  [aux_sym_hunks_repeat1] = "hunks_repeat1",
  [aux_sym_changes_repeat1] = "changes_repeat1",
  [aux_sym_changes_repeat2] = "changes_repeat2",
  [aux_sym_filename_repeat1] = "filename_repeat1",
  [alias_sym_score] = "score",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym_source_token1] = aux_sym_source_token1,
  [anon_sym_diff] = anon_sym_diff,
  [aux_sym_command_token1] = aux_sym_command_token1,
  [anon_sym_new] = anon_sym_new,
  [anon_sym_deleted] = anon_sym_deleted,
  [anon_sym_file] = anon_sym_file,
  [anon_sym_mode] = anon_sym_mode,
  [anon_sym_old] = anon_sym_old,
  [anon_sym_rename] = anon_sym_rename,
  [anon_sym_from] = anon_sym_from,
  [anon_sym_to] = anon_sym_to,
  [anon_sym_Binary] = anon_sym_Binary,
  [anon_sym_files] = anon_sym_files,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_differ] = anon_sym_differ,
  [anon_sym_index] = anon_sym_index,
  [anon_sym_DOT_DOT] = anon_sym_DOT_DOT,
  [anon_sym_similarity] = anon_sym_similarity,
  [anon_sym_index2] = anon_sym_index,
  [aux_sym_similarity_token1] = aux_sym_similarity_token1,
  [anon_sym_PERCENT] = anon_sym_PERCENT,
  [anon_sym_DASH_DASH_DASH] = anon_sym_DASH_DASH_DASH,
  [anon_sym_PLUS_PLUS_PLUS] = anon_sym_PLUS_PLUS_PLUS,
  [anon_sym_AT_AT] = anon_sym_AT_AT,
  [anon_sym_AT_AT2] = anon_sym_AT_AT,
  [aux_sym_location_token1] = aux_sym_location_token1,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_PLUS_PLUS] = anon_sym_PLUS_PLUS,
  [anon_sym_PLUS_PLUS_PLUS_PLUS] = anon_sym_PLUS_PLUS_PLUS_PLUS,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_DASH_DASH] = anon_sym_DASH_DASH,
  [anon_sym_DASH_DASH_DASH_DASH] = anon_sym_DASH_DASH_DASH_DASH,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [anon_sym_POUND] = anon_sym_POUND,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [sym_linerange] = sym_linerange,
  [aux_sym_filename_token1] = aux_sym_filename_token1,
  [sym_commit] = sym_commit,
  [sym_source] = sym_source,
  [sym__line] = sym__line,
  [sym_block] = sym_block,
  [sym_hunks] = sym_hunks,
  [sym_hunk] = sym_hunk,
  [sym_changes] = sym_changes,
  [sym_command] = sym_command,
  [sym_file_change] = sym_file_change,
  [sym_binary_change] = sym_binary_change,
  [sym_index] = sym_index,
  [sym_similarity] = sym_similarity,
  [sym_old_file] = sym_old_file,
  [sym_new_file] = sym_new_file,
  [sym_location] = sym_location,
  [sym_addition] = sym_addition,
  [sym_deletion] = sym_deletion,
  [sym_change] = sym_change,
  [sym_context] = sym_context,
  [sym_comment] = sym_comment,
  [sym_special] = sym_special,
  [sym_filename] = sym_filename,
  [sym_mode] = sym_mode,
  [aux_sym_source_repeat1] = aux_sym_source_repeat1,
  [aux_sym_block_repeat1] = aux_sym_block_repeat1,
  [aux_sym_hunks_repeat1] = aux_sym_hunks_repeat1,
  [aux_sym_changes_repeat1] = aux_sym_changes_repeat1,
  [aux_sym_changes_repeat2] = aux_sym_changes_repeat2,
  [aux_sym_filename_repeat1] = aux_sym_filename_repeat1,
  [alias_sym_score] = alias_sym_score,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_diff] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_command_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_new] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_deleted] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_file] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mode] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_old] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_rename] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_from] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_to] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Binary] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_files] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_differ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_index] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_similarity] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_index2] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_similarity_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_PLUS_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT_AT2] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_location_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS_PLUS_PLUS_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_DASH_DASH_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_linerange] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_filename_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_commit] = {
    .visible = true,
    .named = true,
  },
  [sym_source] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_hunks] = {
    .visible = true,
    .named = true,
  },
  [sym_hunk] = {
    .visible = true,
    .named = true,
  },
  [sym_changes] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_file_change] = {
    .visible = true,
    .named = true,
  },
  [sym_binary_change] = {
    .visible = true,
    .named = true,
  },
  [sym_index] = {
    .visible = true,
    .named = true,
  },
  [sym_similarity] = {
    .visible = true,
    .named = true,
  },
  [sym_old_file] = {
    .visible = true,
    .named = true,
  },
  [sym_new_file] = {
    .visible = true,
    .named = true,
  },
  [sym_location] = {
    .visible = true,
    .named = true,
  },
  [sym_addition] = {
    .visible = true,
    .named = true,
  },
  [sym_deletion] = {
    .visible = true,
    .named = true,
  },
  [sym_change] = {
    .visible = true,
    .named = true,
  },
  [sym_context] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_special] = {
    .visible = true,
    .named = true,
  },
  [sym_filename] = {
    .visible = true,
    .named = true,
  },
  [sym_mode] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_hunks_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_changes_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_changes_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_filename_repeat1] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_score] = {
    .visible = true,
    .named = true,
  },
};

enum ts_field_identifiers {
  field_changes = 1,
  field_location = 2,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_changes] = "changes",
  [field_location] = "location",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [2] = {.index = 0, .length = 1},
  [3] = {.index = 1, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_location, 0},
  [1] =
    {field_changes, 2},
    {field_location, 0},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [2] = alias_sym_score,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 23,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 25,
  [41] = 23,
  [42] = 25,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 91,
  [92] = 92,
  [93] = 93,
  [94] = 94,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(92);
      ADVANCE_MAP(
        '\n', 93,
        '\r', 1,
        '!', 171,
        '#', 173,
        '%', 155,
        '+', 163,
        '-', 167,
        '.', 4,
        '<', 170,
        '>', 166,
        '@', 5,
        'B', 40,
        '\\', 174,
        'a', 57,
        'd', 18,
        'f', 41,
        'i', 59,
        'm', 64,
        'n', 20,
        'o', 49,
        'r', 29,
        's', 39,
        't', 62,
        'b', 84,
        'c', 84,
        'e', 84,
      );
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(86);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(125);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(93);
      END_STATE();
    case 2:
      if (lookahead == '+') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(175);
      END_STATE();
    case 3:
      if (lookahead == '+') ADVANCE(157);
      END_STATE();
    case 4:
      if (lookahead == '.') ADVANCE(112);
      END_STATE();
    case 5:
      if (lookahead == '@') ADVANCE(159);
      END_STATE();
    case 6:
      if (lookahead == '@') ADVANCE(160);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(65);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(182);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') SKIP(8);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(184);
      END_STATE();
    case 9:
      if (lookahead == 'a') ADVANCE(67);
      END_STATE();
    case 10:
      if (lookahead == 'a') ADVANCE(56);
      END_STATE();
    case 11:
      if (lookahead == 'd') ADVANCE(107);
      END_STATE();
    case 12:
      if (lookahead == 'd') ADVANCE(101);
      END_STATE();
    case 13:
      if (lookahead == 'd') ADVANCE(97);
      END_STATE();
    case 14:
      if (lookahead == 'd') ADVANCE(181);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') SKIP(14);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(184);
      END_STATE();
    case 15:
      if (lookahead == 'd') ADVANCE(23);
      END_STATE();
    case 16:
      if (lookahead == 'd') ADVANCE(24);
      END_STATE();
    case 17:
      if (lookahead == 'd') ADVANCE(28);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(48);
      if (lookahead == 'i') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(83);
      END_STATE();
    case 19:
      if (lookahead == 'e') ADVANCE(48);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(83);
      END_STATE();
    case 20:
      if (lookahead == 'e') ADVANCE(71);
      END_STATE();
    case 21:
      if (lookahead == 'e') ADVANCE(70);
      END_STATE();
    case 22:
      if (lookahead == 'e') ADVANCE(99);
      END_STATE();
    case 23:
      if (lookahead == 'e') ADVANCE(72);
      END_STATE();
    case 24:
      if (lookahead == 'e') ADVANCE(100);
      END_STATE();
    case 25:
      if (lookahead == 'e') ADVANCE(102);
      END_STATE();
    case 26:
      if (lookahead == 'e') ADVANCE(98);
      END_STATE();
    case 27:
      if (lookahead == 'e') ADVANCE(68);
      END_STATE();
    case 28:
      if (lookahead == 'e') ADVANCE(73);
      END_STATE();
    case 29:
      if (lookahead == 'e') ADVANCE(60);
      END_STATE();
    case 30:
      if (lookahead == 'e') ADVANCE(66);
      END_STATE();
    case 31:
      if (lookahead == 'e') ADVANCE(13);
      END_STATE();
    case 32:
      if (lookahead == 'e') ADVANCE(47);
      END_STATE();
    case 33:
      if (lookahead == 'e') ADVANCE(47);
      if (lookahead == 'i') ADVANCE(36);
      END_STATE();
    case 34:
      if (lookahead == 'f') ADVANCE(94);
      END_STATE();
    case 35:
      if (lookahead == 'f') ADVANCE(46);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') SKIP(35);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'e')) ADVANCE(84);
      END_STATE();
    case 36:
      if (lookahead == 'f') ADVANCE(34);
      END_STATE();
    case 37:
      if (lookahead == 'f') ADVANCE(38);
      END_STATE();
    case 38:
      if (lookahead == 'f') ADVANCE(30);
      END_STATE();
    case 39:
      if (lookahead == 'i') ADVANCE(55);
      END_STATE();
    case 40:
      if (lookahead == 'i') ADVANCE(58);
      END_STATE();
    case 41:
      if (lookahead == 'i') ADVANCE(50);
      if (lookahead == 'r') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(83);
      END_STATE();
    case 42:
      if (lookahead == 'i') ADVANCE(69);
      END_STATE();
    case 43:
      if (lookahead == 'i') ADVANCE(53);
      END_STATE();
    case 44:
      if (lookahead == 'i') ADVANCE(37);
      END_STATE();
    case 45:
      if (lookahead == 'i') ADVANCE(51);
      END_STATE();
    case 46:
      if (lookahead == 'i') ADVANCE(52);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(83);
      END_STATE();
    case 47:
      if (lookahead == 'l') ADVANCE(21);
      END_STATE();
    case 48:
      if (lookahead == 'l') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(82);
      END_STATE();
    case 49:
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 50:
      if (lookahead == 'l') ADVANCE(22);
      END_STATE();
    case 51:
      if (lookahead == 'l') ADVANCE(26);
      END_STATE();
    case 52:
      if (lookahead == 'l') ADVANCE(27);
      END_STATE();
    case 53:
      if (lookahead == 'l') ADVANCE(9);
      END_STATE();
    case 54:
      if (lookahead == 'm') ADVANCE(103);
      END_STATE();
    case 55:
      if (lookahead == 'm') ADVANCE(43);
      END_STATE();
    case 56:
      if (lookahead == 'm') ADVANCE(25);
      END_STATE();
    case 57:
      if (lookahead == 'n') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(83);
      END_STATE();
    case 58:
      if (lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 59:
      if (lookahead == 'n') ADVANCE(15);
      END_STATE();
    case 60:
      if (lookahead == 'n') ADVANCE(10);
      END_STATE();
    case 61:
      if (lookahead == 'n') ADVANCE(17);
      END_STATE();
    case 62:
      if (lookahead == 'o') ADVANCE(104);
      END_STATE();
    case 63:
      if (lookahead == 'o') ADVANCE(54);
      END_STATE();
    case 64:
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 65:
      if (lookahead == 'r') ADVANCE(74);
      END_STATE();
    case 66:
      if (lookahead == 'r') ADVANCE(109);
      END_STATE();
    case 67:
      if (lookahead == 'r') ADVANCE(42);
      END_STATE();
    case 68:
      if (lookahead == 's') ADVANCE(106);
      END_STATE();
    case 69:
      if (lookahead == 't') ADVANCE(75);
      END_STATE();
    case 70:
      if (lookahead == 't') ADVANCE(31);
      END_STATE();
    case 71:
      if (lookahead == 'w') ADVANCE(96);
      END_STATE();
    case 72:
      if (lookahead == 'x') ADVANCE(111);
      END_STATE();
    case 73:
      if (lookahead == 'x') ADVANCE(114);
      END_STATE();
    case 74:
      if (lookahead == 'y') ADVANCE(105);
      END_STATE();
    case 75:
      if (lookahead == 'y') ADVANCE(113);
      END_STATE();
    case 76:
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') SKIP(76);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 77:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(175);
      END_STATE();
    case 78:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(176);
      END_STATE();
    case 79:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(218);
      END_STATE();
    case 80:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(79);
      END_STATE();
    case 81:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(80);
      END_STATE();
    case 82:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(81);
      END_STATE();
    case 83:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(82);
      END_STATE();
    case 84:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(83);
      END_STATE();
    case 85:
      if (eof) ADVANCE(92);
      ADVANCE_MAP(
        '\n', 93,
        '\r', 1,
        ' ', 172,
        '!', 171,
        '#', 173,
        '+', 163,
        '-', 167,
        '<', 170,
        '>', 166,
        '@', 5,
        'B', 40,
        '\\', 174,
        'd', 33,
        'i', 59,
        'n', 20,
        'o', 49,
        'r', 29,
        's', 39,
      );
      if (('\t' <= lookahead && lookahead <= '\f')) SKIP(89);
      END_STATE();
    case 86:
      if (eof) ADVANCE(92);
      ADVANCE_MAP(
        '\n', 93,
        '\r', 1,
        '%', 155,
        '.', 4,
        '@', 6,
        'a', 57,
        'd', 19,
        'f', 41,
        'i', 61,
        'm', 64,
        'n', 20,
        'o', 49,
        'r', 29,
        't', 62,
        'b', 84,
        'c', 84,
        'e', 84,
      );
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(86);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(125);
      END_STATE();
    case 87:
      if (eof) ADVANCE(92);
      ADVANCE_MAP(
        '\n', 93,
        '\r', 1,
        '+', 2,
        '-', 77,
        '@', 6,
        'd', 44,
        'f', 45,
        'i', 61,
        'm', 64,
      );
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(88);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(154);
      END_STATE();
    case 88:
      if (eof) ADVANCE(92);
      ADVANCE_MAP(
        '\n', 93,
        '\r', 1,
        '@', 6,
        'd', 44,
        'f', 45,
        'i', 61,
        'm', 64,
        '+', 77,
        '-', 77,
      );
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(88);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(154);
      END_STATE();
    case 89:
      if (eof) ADVANCE(92);
      if (lookahead == '\n') ADVANCE(93);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == 'd') ADVANCE(32);
      if (lookahead == 'n') ADVANCE(20);
      if (lookahead == 'o') ADVANCE(49);
      if (lookahead == 'r') ADVANCE(29);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(89);
      END_STATE();
    case 90:
      if (eof) ADVANCE(92);
      if (lookahead == '\n') ADVANCE(93);
      if (lookahead == '\r') ADVANCE(1);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(90);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(184);
      END_STATE();
    case 91:
      if (eof) ADVANCE(92);
      if (lookahead == '\n') ADVANCE(93);
      if (lookahead == '\r') ADVANCE(1);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') ADVANCE(161);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(162);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_source_token1);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_diff);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym_command_token1);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(95);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_new);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_deleted);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(anon_sym_file);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_file);
      if (lookahead == 's') ADVANCE(106);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_mode);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_old);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_rename);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(anon_sym_from);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_to);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(anon_sym_Binary);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_files);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_and);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(184);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_differ);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_differ);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(184);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(anon_sym_index);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(anon_sym_DOT_DOT);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(anon_sym_similarity);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(anon_sym_index2);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(218);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(153);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(185);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(154);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(79);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(115);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(186);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(116);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(80);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(117);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(187);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(118);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(81);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(119);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(188);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(120);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(82);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(121);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(189);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(122);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(83);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(123);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(190);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(124);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(191);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(126);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(192);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(127);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(193);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(128);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(194);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(129);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(195);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(130);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(196);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(131);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(197);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(132);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(198);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(133);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(199);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(134);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(200);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(135);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(201);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(136);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(202);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(137);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(203);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(138);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(204);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(139);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(205);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(140);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(206);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(141);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(207);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(142);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(208);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(143);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(209);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(144);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(210);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(145);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(211);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(146);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(212);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(147);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(213);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(148);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(214);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(149);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(215);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(150);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(216);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(151);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('a' <= lookahead && lookahead <= 'f')) ADVANCE(217);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(152);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(aux_sym_similarity_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(154);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(anon_sym_PERCENT);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_DASH);
      if (lookahead == '-') ADVANCE(169);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(anon_sym_PLUS_PLUS_PLUS);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(anon_sym_PLUS_PLUS_PLUS);
      if (lookahead == '+') ADVANCE(165);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(anon_sym_AT_AT);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(anon_sym_AT_AT2);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(aux_sym_location_token1);
      if (lookahead == '\t' ||
          lookahead == 0x0b ||
          lookahead == '\f' ||
          lookahead == ' ') ADVANCE(161);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(162);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(aux_sym_location_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(162);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (lookahead == '+') ADVANCE(164);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(anon_sym_PLUS_PLUS);
      if (lookahead == '+') ADVANCE(158);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(anon_sym_PLUS_PLUS_PLUS_PLUS);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '-') ADVANCE(168);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(anon_sym_DASH_DASH);
      if (lookahead == '-') ADVANCE(156);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(anon_sym_DASH_DASH_DASH_DASH);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 171:
      ACCEPT_TOKEN(anon_sym_BANG);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(anon_sym_SPACE);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(sym_linerange);
      if (lookahead == ',') ADVANCE(78);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(175);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(sym_linerange);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(176);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(aux_sym_filename_token1);
      if (lookahead == 'd') ADVANCE(108);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(184);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(aux_sym_filename_token1);
      if (lookahead == 'e') ADVANCE(183);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(184);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(aux_sym_filename_token1);
      if (lookahead == 'f') ADVANCE(178);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(184);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(aux_sym_filename_token1);
      if (lookahead == 'f') ADVANCE(179);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(184);
      END_STATE();
    case 181:
      ACCEPT_TOKEN(aux_sym_filename_token1);
      if (lookahead == 'i') ADVANCE(180);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(184);
      END_STATE();
    case 182:
      ACCEPT_TOKEN(aux_sym_filename_token1);
      if (lookahead == 'n') ADVANCE(177);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(184);
      END_STATE();
    case 183:
      ACCEPT_TOKEN(aux_sym_filename_token1);
      if (lookahead == 'r') ADVANCE(110);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(184);
      END_STATE();
    case 184:
      ACCEPT_TOKEN(aux_sym_filename_token1);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(184);
      END_STATE();
    case 185:
      ACCEPT_TOKEN(sym_commit);
      END_STATE();
    case 186:
      ACCEPT_TOKEN(sym_commit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(185);
      END_STATE();
    case 187:
      ACCEPT_TOKEN(sym_commit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(186);
      END_STATE();
    case 188:
      ACCEPT_TOKEN(sym_commit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(187);
      END_STATE();
    case 189:
      ACCEPT_TOKEN(sym_commit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(188);
      END_STATE();
    case 190:
      ACCEPT_TOKEN(sym_commit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(189);
      END_STATE();
    case 191:
      ACCEPT_TOKEN(sym_commit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(190);
      END_STATE();
    case 192:
      ACCEPT_TOKEN(sym_commit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(191);
      END_STATE();
    case 193:
      ACCEPT_TOKEN(sym_commit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(192);
      END_STATE();
    case 194:
      ACCEPT_TOKEN(sym_commit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(193);
      END_STATE();
    case 195:
      ACCEPT_TOKEN(sym_commit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(194);
      END_STATE();
    case 196:
      ACCEPT_TOKEN(sym_commit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(195);
      END_STATE();
    case 197:
      ACCEPT_TOKEN(sym_commit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(196);
      END_STATE();
    case 198:
      ACCEPT_TOKEN(sym_commit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(197);
      END_STATE();
    case 199:
      ACCEPT_TOKEN(sym_commit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(198);
      END_STATE();
    case 200:
      ACCEPT_TOKEN(sym_commit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(199);
      END_STATE();
    case 201:
      ACCEPT_TOKEN(sym_commit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(200);
      END_STATE();
    case 202:
      ACCEPT_TOKEN(sym_commit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(201);
      END_STATE();
    case 203:
      ACCEPT_TOKEN(sym_commit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(202);
      END_STATE();
    case 204:
      ACCEPT_TOKEN(sym_commit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(203);
      END_STATE();
    case 205:
      ACCEPT_TOKEN(sym_commit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(204);
      END_STATE();
    case 206:
      ACCEPT_TOKEN(sym_commit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(205);
      END_STATE();
    case 207:
      ACCEPT_TOKEN(sym_commit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(206);
      END_STATE();
    case 208:
      ACCEPT_TOKEN(sym_commit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(207);
      END_STATE();
    case 209:
      ACCEPT_TOKEN(sym_commit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(208);
      END_STATE();
    case 210:
      ACCEPT_TOKEN(sym_commit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(209);
      END_STATE();
    case 211:
      ACCEPT_TOKEN(sym_commit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(210);
      END_STATE();
    case 212:
      ACCEPT_TOKEN(sym_commit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(211);
      END_STATE();
    case 213:
      ACCEPT_TOKEN(sym_commit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(212);
      END_STATE();
    case 214:
      ACCEPT_TOKEN(sym_commit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(213);
      END_STATE();
    case 215:
      ACCEPT_TOKEN(sym_commit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(214);
      END_STATE();
    case 216:
      ACCEPT_TOKEN(sym_commit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(215);
      END_STATE();
    case 217:
      ACCEPT_TOKEN(sym_commit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(216);
      END_STATE();
    case 218:
      ACCEPT_TOKEN(sym_commit);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(217);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 85},
  [2] = {.lex_state = 85},
  [3] = {.lex_state = 85},
  [4] = {.lex_state = 85},
  [5] = {.lex_state = 85},
  [6] = {.lex_state = 85},
  [7] = {.lex_state = 85},
  [8] = {.lex_state = 85},
  [9] = {.lex_state = 85},
  [10] = {.lex_state = 85},
  [11] = {.lex_state = 85},
  [12] = {.lex_state = 85},
  [13] = {.lex_state = 85},
  [14] = {.lex_state = 85},
  [15] = {.lex_state = 85},
  [16] = {.lex_state = 85},
  [17] = {.lex_state = 85},
  [18] = {.lex_state = 85},
  [19] = {.lex_state = 90},
  [20] = {.lex_state = 90},
  [21] = {.lex_state = 85},
  [22] = {.lex_state = 85},
  [23] = {.lex_state = 90},
  [24] = {.lex_state = 87},
  [25] = {.lex_state = 90},
  [26] = {.lex_state = 14},
  [27] = {.lex_state = 91},
  [28] = {.lex_state = 91},
  [29] = {.lex_state = 90},
  [30] = {.lex_state = 91},
  [31] = {.lex_state = 90},
  [32] = {.lex_state = 91},
  [33] = {.lex_state = 91},
  [34] = {.lex_state = 91},
  [35] = {.lex_state = 90},
  [36] = {.lex_state = 90},
  [37] = {.lex_state = 90},
  [38] = {.lex_state = 90},
  [39] = {.lex_state = 91},
  [40] = {.lex_state = 8},
  [41] = {.lex_state = 8},
  [42] = {.lex_state = 14},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 87},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 87},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 87},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
  [63] = {.lex_state = 87},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 87},
  [66] = {.lex_state = 0},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 87},
  [69] = {.lex_state = 87},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 35},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 76},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 87},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 35},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 35},
  [86] = {.lex_state = 87},
  [87] = {.lex_state = 87},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 87},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 87},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym_source_token1] = ACTIONS(1),
    [anon_sym_diff] = ACTIONS(1),
    [anon_sym_new] = ACTIONS(1),
    [anon_sym_deleted] = ACTIONS(1),
    [anon_sym_file] = ACTIONS(1),
    [anon_sym_mode] = ACTIONS(1),
    [anon_sym_old] = ACTIONS(1),
    [anon_sym_rename] = ACTIONS(1),
    [anon_sym_from] = ACTIONS(1),
    [anon_sym_to] = ACTIONS(1),
    [anon_sym_Binary] = ACTIONS(1),
    [anon_sym_files] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_index] = ACTIONS(1),
    [anon_sym_DOT_DOT] = ACTIONS(1),
    [anon_sym_similarity] = ACTIONS(1),
    [anon_sym_index2] = ACTIONS(1),
    [aux_sym_similarity_token1] = ACTIONS(1),
    [anon_sym_PERCENT] = ACTIONS(1),
    [anon_sym_DASH_DASH_DASH] = ACTIONS(1),
    [anon_sym_PLUS_PLUS_PLUS] = ACTIONS(1),
    [anon_sym_AT_AT] = ACTIONS(1),
    [anon_sym_AT_AT2] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_PLUS_PLUS] = ACTIONS(1),
    [anon_sym_PLUS_PLUS_PLUS_PLUS] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_DASH_DASH] = ACTIONS(1),
    [anon_sym_DASH_DASH_DASH_DASH] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [sym_commit] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source] = STATE(93),
    [sym__line] = STATE(51),
    [sym_block] = STATE(2),
    [sym_command] = STATE(70),
    [sym_file_change] = STATE(51),
    [sym_binary_change] = STATE(51),
    [sym_index] = STATE(51),
    [sym_similarity] = STATE(51),
    [sym_old_file] = STATE(51),
    [sym_new_file] = STATE(51),
    [sym_location] = STATE(51),
    [sym_addition] = STATE(51),
    [sym_deletion] = STATE(51),
    [sym_change] = STATE(51),
    [sym_context] = STATE(51),
    [sym_comment] = STATE(51),
    [sym_special] = STATE(51),
    [aux_sym_source_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [aux_sym_source_token1] = ACTIONS(5),
    [anon_sym_diff] = ACTIONS(7),
    [anon_sym_new] = ACTIONS(9),
    [anon_sym_deleted] = ACTIONS(11),
    [anon_sym_old] = ACTIONS(13),
    [anon_sym_rename] = ACTIONS(15),
    [anon_sym_Binary] = ACTIONS(17),
    [anon_sym_index] = ACTIONS(19),
    [anon_sym_similarity] = ACTIONS(21),
    [anon_sym_DASH_DASH_DASH] = ACTIONS(23),
    [anon_sym_PLUS_PLUS_PLUS] = ACTIONS(25),
    [anon_sym_AT_AT] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(29),
    [anon_sym_PLUS_PLUS] = ACTIONS(29),
    [anon_sym_PLUS_PLUS_PLUS_PLUS] = ACTIONS(31),
    [anon_sym_GT] = ACTIONS(31),
    [anon_sym_DASH] = ACTIONS(33),
    [anon_sym_DASH_DASH] = ACTIONS(33),
    [anon_sym_DASH_DASH_DASH_DASH] = ACTIONS(35),
    [anon_sym_LT] = ACTIONS(35),
    [anon_sym_BANG] = ACTIONS(37),
    [anon_sym_SPACE] = ACTIONS(39),
    [anon_sym_POUND] = ACTIONS(41),
    [anon_sym_BSLASH] = ACTIONS(43),
  },
  [STATE(2)] = {
    [sym__line] = STATE(56),
    [sym_block] = STATE(3),
    [sym_command] = STATE(70),
    [sym_file_change] = STATE(56),
    [sym_binary_change] = STATE(56),
    [sym_index] = STATE(56),
    [sym_similarity] = STATE(56),
    [sym_old_file] = STATE(56),
    [sym_new_file] = STATE(56),
    [sym_location] = STATE(56),
    [sym_addition] = STATE(56),
    [sym_deletion] = STATE(56),
    [sym_change] = STATE(56),
    [sym_context] = STATE(56),
    [sym_comment] = STATE(56),
    [sym_special] = STATE(56),
    [aux_sym_source_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(45),
    [aux_sym_source_token1] = ACTIONS(47),
    [anon_sym_diff] = ACTIONS(7),
    [anon_sym_new] = ACTIONS(9),
    [anon_sym_deleted] = ACTIONS(11),
    [anon_sym_old] = ACTIONS(13),
    [anon_sym_rename] = ACTIONS(15),
    [anon_sym_Binary] = ACTIONS(17),
    [anon_sym_index] = ACTIONS(19),
    [anon_sym_similarity] = ACTIONS(21),
    [anon_sym_DASH_DASH_DASH] = ACTIONS(23),
    [anon_sym_PLUS_PLUS_PLUS] = ACTIONS(25),
    [anon_sym_AT_AT] = ACTIONS(27),
    [anon_sym_PLUS] = ACTIONS(29),
    [anon_sym_PLUS_PLUS] = ACTIONS(29),
    [anon_sym_PLUS_PLUS_PLUS_PLUS] = ACTIONS(31),
    [anon_sym_GT] = ACTIONS(31),
    [anon_sym_DASH] = ACTIONS(33),
    [anon_sym_DASH_DASH] = ACTIONS(33),
    [anon_sym_DASH_DASH_DASH_DASH] = ACTIONS(35),
    [anon_sym_LT] = ACTIONS(35),
    [anon_sym_BANG] = ACTIONS(37),
    [anon_sym_SPACE] = ACTIONS(39),
    [anon_sym_POUND] = ACTIONS(41),
    [anon_sym_BSLASH] = ACTIONS(43),
  },
  [STATE(3)] = {
    [sym__line] = STATE(82),
    [sym_block] = STATE(3),
    [sym_command] = STATE(70),
    [sym_file_change] = STATE(82),
    [sym_binary_change] = STATE(82),
    [sym_index] = STATE(82),
    [sym_similarity] = STATE(82),
    [sym_old_file] = STATE(82),
    [sym_new_file] = STATE(82),
    [sym_location] = STATE(82),
    [sym_addition] = STATE(82),
    [sym_deletion] = STATE(82),
    [sym_change] = STATE(82),
    [sym_context] = STATE(82),
    [sym_comment] = STATE(82),
    [sym_special] = STATE(82),
    [aux_sym_source_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(49),
    [aux_sym_source_token1] = ACTIONS(51),
    [anon_sym_diff] = ACTIONS(54),
    [anon_sym_new] = ACTIONS(57),
    [anon_sym_deleted] = ACTIONS(60),
    [anon_sym_old] = ACTIONS(63),
    [anon_sym_rename] = ACTIONS(66),
    [anon_sym_Binary] = ACTIONS(69),
    [anon_sym_index] = ACTIONS(72),
    [anon_sym_similarity] = ACTIONS(75),
    [anon_sym_DASH_DASH_DASH] = ACTIONS(78),
    [anon_sym_PLUS_PLUS_PLUS] = ACTIONS(81),
    [anon_sym_AT_AT] = ACTIONS(84),
    [anon_sym_PLUS] = ACTIONS(87),
    [anon_sym_PLUS_PLUS] = ACTIONS(87),
    [anon_sym_PLUS_PLUS_PLUS_PLUS] = ACTIONS(90),
    [anon_sym_GT] = ACTIONS(90),
    [anon_sym_DASH] = ACTIONS(93),
    [anon_sym_DASH_DASH] = ACTIONS(93),
    [anon_sym_DASH_DASH_DASH_DASH] = ACTIONS(96),
    [anon_sym_LT] = ACTIONS(96),
    [anon_sym_BANG] = ACTIONS(99),
    [anon_sym_SPACE] = ACTIONS(102),
    [anon_sym_POUND] = ACTIONS(105),
    [anon_sym_BSLASH] = ACTIONS(108),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 14,
    ACTIONS(37), 1,
      anon_sym_BANG,
    ACTIONS(39), 1,
      anon_sym_SPACE,
    ACTIONS(43), 1,
      anon_sym_BSLASH,
    ACTIONS(115), 1,
      anon_sym_DASH_DASH_DASH,
    ACTIONS(117), 1,
      anon_sym_PLUS_PLUS_PLUS,
    STATE(7), 1,
      aux_sym_changes_repeat2,
    STATE(16), 1,
      sym_changes,
    ACTIONS(29), 2,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
    ACTIONS(31), 2,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
      anon_sym_GT,
    ACTIONS(33), 2,
      anon_sym_DASH,
      anon_sym_DASH_DASH,
    ACTIONS(35), 2,
      anon_sym_DASH_DASH_DASH_DASH,
      anon_sym_LT,
    ACTIONS(113), 5,
      aux_sym_source_token1,
      anon_sym_new,
      anon_sym_deleted,
      anon_sym_old,
      anon_sym_rename,
    STATE(58), 5,
      sym_addition,
      sym_deletion,
      sym_change,
      sym_context,
      sym_special,
    ACTIONS(111), 7,
      ts_builtin_sym_end,
      anon_sym_diff,
      anon_sym_Binary,
      anon_sym_index,
      anon_sym_similarity,
      anon_sym_AT_AT,
      anon_sym_POUND,
  [61] = 13,
    ACTIONS(9), 1,
      anon_sym_new,
    ACTIONS(11), 1,
      anon_sym_deleted,
    ACTIONS(13), 1,
      anon_sym_old,
    ACTIONS(15), 1,
      anon_sym_rename,
    ACTIONS(17), 1,
      anon_sym_Binary,
    ACTIONS(19), 1,
      anon_sym_index,
    ACTIONS(21), 1,
      anon_sym_similarity,
    ACTIONS(123), 1,
      anon_sym_DASH_DASH_DASH,
    STATE(9), 1,
      aux_sym_block_repeat1,
    STATE(92), 1,
      sym_old_file,
    STATE(79), 4,
      sym_file_change,
      sym_binary_change,
      sym_index,
      sym_similarity,
    ACTIONS(121), 6,
      aux_sym_source_token1,
      anon_sym_PLUS_PLUS_PLUS,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH,
      anon_sym_DASH_DASH,
    ACTIONS(119), 11,
      ts_builtin_sym_end,
      anon_sym_diff,
      anon_sym_AT_AT,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
      anon_sym_GT,
      anon_sym_DASH_DASH_DASH_DASH,
      anon_sym_LT,
      anon_sym_BANG,
      anon_sym_SPACE,
      anon_sym_POUND,
      anon_sym_BSLASH,
  [119] = 13,
    ACTIONS(9), 1,
      anon_sym_new,
    ACTIONS(11), 1,
      anon_sym_deleted,
    ACTIONS(13), 1,
      anon_sym_old,
    ACTIONS(15), 1,
      anon_sym_rename,
    ACTIONS(17), 1,
      anon_sym_Binary,
    ACTIONS(19), 1,
      anon_sym_index,
    ACTIONS(21), 1,
      anon_sym_similarity,
    ACTIONS(123), 1,
      anon_sym_DASH_DASH_DASH,
    STATE(5), 1,
      aux_sym_block_repeat1,
    STATE(80), 1,
      sym_old_file,
    STATE(79), 4,
      sym_file_change,
      sym_binary_change,
      sym_index,
      sym_similarity,
    ACTIONS(127), 6,
      aux_sym_source_token1,
      anon_sym_PLUS_PLUS_PLUS,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH,
      anon_sym_DASH_DASH,
    ACTIONS(125), 11,
      ts_builtin_sym_end,
      anon_sym_diff,
      anon_sym_AT_AT,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
      anon_sym_GT,
      anon_sym_DASH_DASH_DASH_DASH,
      anon_sym_LT,
      anon_sym_BANG,
      anon_sym_SPACE,
      anon_sym_POUND,
      anon_sym_BSLASH,
  [177] = 13,
    ACTIONS(37), 1,
      anon_sym_BANG,
    ACTIONS(39), 1,
      anon_sym_SPACE,
    ACTIONS(43), 1,
      anon_sym_BSLASH,
    ACTIONS(115), 1,
      anon_sym_DASH_DASH_DASH,
    ACTIONS(117), 1,
      anon_sym_PLUS_PLUS_PLUS,
    STATE(8), 1,
      aux_sym_changes_repeat2,
    ACTIONS(29), 2,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
    ACTIONS(31), 2,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
      anon_sym_GT,
    ACTIONS(33), 2,
      anon_sym_DASH,
      anon_sym_DASH_DASH,
    ACTIONS(35), 2,
      anon_sym_DASH_DASH_DASH_DASH,
      anon_sym_LT,
    ACTIONS(131), 5,
      aux_sym_source_token1,
      anon_sym_new,
      anon_sym_deleted,
      anon_sym_old,
      anon_sym_rename,
    STATE(58), 5,
      sym_addition,
      sym_deletion,
      sym_change,
      sym_context,
      sym_special,
    ACTIONS(129), 7,
      ts_builtin_sym_end,
      anon_sym_diff,
      anon_sym_Binary,
      anon_sym_index,
      anon_sym_similarity,
      anon_sym_AT_AT,
      anon_sym_POUND,
  [235] = 13,
    ACTIONS(137), 1,
      anon_sym_DASH_DASH_DASH,
    ACTIONS(140), 1,
      anon_sym_PLUS_PLUS_PLUS,
    ACTIONS(155), 1,
      anon_sym_BANG,
    ACTIONS(158), 1,
      anon_sym_SPACE,
    ACTIONS(161), 1,
      anon_sym_BSLASH,
    STATE(8), 1,
      aux_sym_changes_repeat2,
    ACTIONS(143), 2,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
    ACTIONS(146), 2,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
      anon_sym_GT,
    ACTIONS(149), 2,
      anon_sym_DASH,
      anon_sym_DASH_DASH,
    ACTIONS(152), 2,
      anon_sym_DASH_DASH_DASH_DASH,
      anon_sym_LT,
    ACTIONS(135), 5,
      aux_sym_source_token1,
      anon_sym_new,
      anon_sym_deleted,
      anon_sym_old,
      anon_sym_rename,
    STATE(58), 5,
      sym_addition,
      sym_deletion,
      sym_change,
      sym_context,
      sym_special,
    ACTIONS(133), 7,
      ts_builtin_sym_end,
      anon_sym_diff,
      anon_sym_Binary,
      anon_sym_index,
      anon_sym_similarity,
      anon_sym_AT_AT,
      anon_sym_POUND,
  [293] = 11,
    ACTIONS(168), 1,
      anon_sym_new,
    ACTIONS(171), 1,
      anon_sym_deleted,
    ACTIONS(174), 1,
      anon_sym_old,
    ACTIONS(177), 1,
      anon_sym_rename,
    ACTIONS(180), 1,
      anon_sym_Binary,
    ACTIONS(183), 1,
      anon_sym_index,
    ACTIONS(186), 1,
      anon_sym_similarity,
    STATE(9), 1,
      aux_sym_block_repeat1,
    STATE(79), 4,
      sym_file_change,
      sym_binary_change,
      sym_index,
      sym_similarity,
    ACTIONS(166), 7,
      aux_sym_source_token1,
      anon_sym_DASH_DASH_DASH,
      anon_sym_PLUS_PLUS_PLUS,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH,
      anon_sym_DASH_DASH,
    ACTIONS(164), 11,
      ts_builtin_sym_end,
      anon_sym_diff,
      anon_sym_AT_AT,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
      anon_sym_GT,
      anon_sym_DASH_DASH_DASH_DASH,
      anon_sym_LT,
      anon_sym_BANG,
      anon_sym_SPACE,
      anon_sym_POUND,
      anon_sym_BSLASH,
  [346] = 5,
    ACTIONS(27), 1,
      anon_sym_AT_AT,
    STATE(77), 1,
      sym_location,
    STATE(11), 2,
      sym_hunk,
      aux_sym_hunks_repeat1,
    ACTIONS(191), 11,
      aux_sym_source_token1,
      anon_sym_new,
      anon_sym_deleted,
      anon_sym_old,
      anon_sym_rename,
      anon_sym_DASH_DASH_DASH,
      anon_sym_PLUS_PLUS_PLUS,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH,
      anon_sym_DASH_DASH,
    ACTIONS(189), 13,
      ts_builtin_sym_end,
      anon_sym_diff,
      anon_sym_Binary,
      anon_sym_index,
      anon_sym_similarity,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
      anon_sym_GT,
      anon_sym_DASH_DASH_DASH_DASH,
      anon_sym_LT,
      anon_sym_BANG,
      anon_sym_SPACE,
      anon_sym_POUND,
      anon_sym_BSLASH,
  [385] = 5,
    ACTIONS(197), 1,
      anon_sym_AT_AT,
    STATE(77), 1,
      sym_location,
    STATE(11), 2,
      sym_hunk,
      aux_sym_hunks_repeat1,
    ACTIONS(195), 11,
      aux_sym_source_token1,
      anon_sym_new,
      anon_sym_deleted,
      anon_sym_old,
      anon_sym_rename,
      anon_sym_DASH_DASH_DASH,
      anon_sym_PLUS_PLUS_PLUS,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH,
      anon_sym_DASH_DASH,
    ACTIONS(193), 13,
      ts_builtin_sym_end,
      anon_sym_diff,
      anon_sym_Binary,
      anon_sym_index,
      anon_sym_similarity,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
      anon_sym_GT,
      anon_sym_DASH_DASH_DASH_DASH,
      anon_sym_LT,
      anon_sym_BANG,
      anon_sym_SPACE,
      anon_sym_POUND,
      anon_sym_BSLASH,
  [424] = 4,
    ACTIONS(202), 1,
      aux_sym_source_token1,
    STATE(12), 1,
      aux_sym_changes_repeat1,
    ACTIONS(205), 10,
      anon_sym_new,
      anon_sym_deleted,
      anon_sym_old,
      anon_sym_rename,
      anon_sym_DASH_DASH_DASH,
      anon_sym_PLUS_PLUS_PLUS,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH,
      anon_sym_DASH_DASH,
    ACTIONS(200), 14,
      ts_builtin_sym_end,
      anon_sym_diff,
      anon_sym_Binary,
      anon_sym_index,
      anon_sym_similarity,
      anon_sym_AT_AT,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
      anon_sym_GT,
      anon_sym_DASH_DASH_DASH_DASH,
      anon_sym_LT,
      anon_sym_BANG,
      anon_sym_SPACE,
      anon_sym_POUND,
      anon_sym_BSLASH,
  [459] = 4,
    ACTIONS(207), 1,
      aux_sym_source_token1,
    STATE(12), 1,
      aux_sym_changes_repeat1,
    ACTIONS(135), 10,
      anon_sym_new,
      anon_sym_deleted,
      anon_sym_old,
      anon_sym_rename,
      anon_sym_DASH_DASH_DASH,
      anon_sym_PLUS_PLUS_PLUS,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH,
      anon_sym_DASH_DASH,
    ACTIONS(133), 14,
      ts_builtin_sym_end,
      anon_sym_diff,
      anon_sym_Binary,
      anon_sym_index,
      anon_sym_similarity,
      anon_sym_AT_AT,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
      anon_sym_GT,
      anon_sym_DASH_DASH_DASH_DASH,
      anon_sym_LT,
      anon_sym_BANG,
      anon_sym_SPACE,
      anon_sym_POUND,
      anon_sym_BSLASH,
  [494] = 2,
    ACTIONS(209), 11,
      aux_sym_source_token1,
      anon_sym_new,
      anon_sym_deleted,
      anon_sym_old,
      anon_sym_rename,
      anon_sym_DASH_DASH_DASH,
      anon_sym_PLUS_PLUS_PLUS,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH,
      anon_sym_DASH_DASH,
    ACTIONS(49), 14,
      ts_builtin_sym_end,
      anon_sym_diff,
      anon_sym_Binary,
      anon_sym_index,
      anon_sym_similarity,
      anon_sym_AT_AT,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
      anon_sym_GT,
      anon_sym_DASH_DASH_DASH_DASH,
      anon_sym_LT,
      anon_sym_BANG,
      anon_sym_SPACE,
      anon_sym_POUND,
      anon_sym_BSLASH,
  [524] = 2,
    ACTIONS(166), 11,
      aux_sym_source_token1,
      anon_sym_new,
      anon_sym_deleted,
      anon_sym_old,
      anon_sym_rename,
      anon_sym_DASH_DASH_DASH,
      anon_sym_PLUS_PLUS_PLUS,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH,
      anon_sym_DASH_DASH,
    ACTIONS(164), 14,
      ts_builtin_sym_end,
      anon_sym_diff,
      anon_sym_Binary,
      anon_sym_index,
      anon_sym_similarity,
      anon_sym_AT_AT,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
      anon_sym_GT,
      anon_sym_DASH_DASH_DASH_DASH,
      anon_sym_LT,
      anon_sym_BANG,
      anon_sym_SPACE,
      anon_sym_POUND,
      anon_sym_BSLASH,
  [554] = 2,
    ACTIONS(213), 11,
      aux_sym_source_token1,
      anon_sym_new,
      anon_sym_deleted,
      anon_sym_old,
      anon_sym_rename,
      anon_sym_DASH_DASH_DASH,
      anon_sym_PLUS_PLUS_PLUS,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH,
      anon_sym_DASH_DASH,
    ACTIONS(211), 14,
      ts_builtin_sym_end,
      anon_sym_diff,
      anon_sym_Binary,
      anon_sym_index,
      anon_sym_similarity,
      anon_sym_AT_AT,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
      anon_sym_GT,
      anon_sym_DASH_DASH_DASH_DASH,
      anon_sym_LT,
      anon_sym_BANG,
      anon_sym_SPACE,
      anon_sym_POUND,
      anon_sym_BSLASH,
  [584] = 2,
    ACTIONS(217), 11,
      aux_sym_source_token1,
      anon_sym_new,
      anon_sym_deleted,
      anon_sym_old,
      anon_sym_rename,
      anon_sym_DASH_DASH_DASH,
      anon_sym_PLUS_PLUS_PLUS,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH,
      anon_sym_DASH_DASH,
    ACTIONS(215), 14,
      ts_builtin_sym_end,
      anon_sym_diff,
      anon_sym_Binary,
      anon_sym_index,
      anon_sym_similarity,
      anon_sym_AT_AT,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
      anon_sym_GT,
      anon_sym_DASH_DASH_DASH_DASH,
      anon_sym_LT,
      anon_sym_BANG,
      anon_sym_SPACE,
      anon_sym_POUND,
      anon_sym_BSLASH,
  [614] = 2,
    ACTIONS(221), 11,
      aux_sym_source_token1,
      anon_sym_new,
      anon_sym_deleted,
      anon_sym_old,
      anon_sym_rename,
      anon_sym_DASH_DASH_DASH,
      anon_sym_PLUS_PLUS_PLUS,
      anon_sym_PLUS,
      anon_sym_PLUS_PLUS,
      anon_sym_DASH,
      anon_sym_DASH_DASH,
    ACTIONS(219), 14,
      ts_builtin_sym_end,
      anon_sym_diff,
      anon_sym_Binary,
      anon_sym_index,
      anon_sym_similarity,
      anon_sym_AT_AT,
      anon_sym_PLUS_PLUS_PLUS_PLUS,
      anon_sym_GT,
      anon_sym_DASH_DASH_DASH_DASH,
      anon_sym_LT,
      anon_sym_BANG,
      anon_sym_SPACE,
      anon_sym_POUND,
      anon_sym_BSLASH,
  [644] = 4,
    ACTIONS(225), 1,
      aux_sym_filename_token1,
    STATE(25), 1,
      aux_sym_filename_repeat1,
    STATE(61), 1,
      sym_filename,
    ACTIONS(223), 2,
      ts_builtin_sym_end,
      aux_sym_source_token1,
  [658] = 4,
    ACTIONS(225), 1,
      aux_sym_filename_token1,
    STATE(25), 1,
      aux_sym_filename_repeat1,
    STATE(59), 1,
      sym_filename,
    ACTIONS(227), 2,
      ts_builtin_sym_end,
      aux_sym_source_token1,
  [672] = 4,
    ACTIONS(27), 1,
      anon_sym_AT_AT,
    STATE(17), 1,
      sym_hunks,
    STATE(77), 1,
      sym_location,
    STATE(10), 2,
      sym_hunk,
      aux_sym_hunks_repeat1,
  [686] = 4,
    ACTIONS(27), 1,
      anon_sym_AT_AT,
    STATE(18), 1,
      sym_hunks,
    STATE(77), 1,
      sym_location,
    STATE(10), 2,
      sym_hunk,
      aux_sym_hunks_repeat1,
  [700] = 3,
    ACTIONS(231), 1,
      aux_sym_filename_token1,
    STATE(23), 1,
      aux_sym_filename_repeat1,
    ACTIONS(229), 2,
      ts_builtin_sym_end,
      aux_sym_source_token1,
  [711] = 3,
    ACTIONS(236), 1,
      aux_sym_similarity_token1,
    STATE(45), 1,
      sym_mode,
    ACTIONS(234), 2,
      ts_builtin_sym_end,
      aux_sym_source_token1,
  [722] = 3,
    ACTIONS(240), 1,
      aux_sym_filename_token1,
    STATE(23), 1,
      aux_sym_filename_repeat1,
    ACTIONS(238), 2,
      ts_builtin_sym_end,
      aux_sym_source_token1,
  [733] = 3,
    ACTIONS(242), 1,
      anon_sym_differ,
    ACTIONS(244), 1,
      aux_sym_filename_token1,
    STATE(26), 1,
      aux_sym_filename_repeat1,
  [743] = 3,
    ACTIONS(223), 1,
      ts_builtin_sym_end,
    ACTIONS(247), 1,
      aux_sym_source_token1,
    ACTIONS(249), 1,
      aux_sym_location_token1,
  [753] = 3,
    ACTIONS(227), 1,
      ts_builtin_sym_end,
    ACTIONS(251), 1,
      aux_sym_source_token1,
    ACTIONS(253), 1,
      aux_sym_location_token1,
  [763] = 3,
    ACTIONS(225), 1,
      aux_sym_filename_token1,
    STATE(25), 1,
      aux_sym_filename_repeat1,
    STATE(59), 1,
      sym_filename,
  [773] = 3,
    ACTIONS(255), 1,
      ts_builtin_sym_end,
    ACTIONS(257), 1,
      aux_sym_source_token1,
    ACTIONS(259), 1,
      aux_sym_location_token1,
  [783] = 3,
    ACTIONS(261), 1,
      aux_sym_filename_token1,
    STATE(42), 1,
      aux_sym_filename_repeat1,
    STATE(94), 1,
      sym_filename,
  [793] = 3,
    ACTIONS(263), 1,
      ts_builtin_sym_end,
    ACTIONS(265), 1,
      aux_sym_source_token1,
    ACTIONS(267), 1,
      aux_sym_location_token1,
  [803] = 3,
    ACTIONS(269), 1,
      ts_builtin_sym_end,
    ACTIONS(271), 1,
      aux_sym_source_token1,
    ACTIONS(273), 1,
      aux_sym_location_token1,
  [813] = 3,
    ACTIONS(275), 1,
      ts_builtin_sym_end,
    ACTIONS(277), 1,
      aux_sym_source_token1,
    ACTIONS(279), 1,
      aux_sym_location_token1,
  [823] = 3,
    ACTIONS(225), 1,
      aux_sym_filename_token1,
    STATE(25), 1,
      aux_sym_filename_repeat1,
    STATE(61), 1,
      sym_filename,
  [833] = 3,
    ACTIONS(225), 1,
      aux_sym_filename_token1,
    STATE(25), 1,
      aux_sym_filename_repeat1,
    STATE(91), 1,
      sym_filename,
  [843] = 3,
    ACTIONS(225), 1,
      aux_sym_filename_token1,
    STATE(25), 1,
      aux_sym_filename_repeat1,
    STATE(66), 1,
      sym_filename,
  [853] = 3,
    ACTIONS(281), 1,
      aux_sym_filename_token1,
    STATE(40), 1,
      aux_sym_filename_repeat1,
    STATE(67), 1,
      sym_filename,
  [863] = 3,
    ACTIONS(283), 1,
      ts_builtin_sym_end,
    ACTIONS(285), 1,
      aux_sym_source_token1,
    ACTIONS(287), 1,
      aux_sym_location_token1,
  [873] = 3,
    ACTIONS(289), 1,
      anon_sym_and,
    ACTIONS(291), 1,
      aux_sym_filename_token1,
    STATE(41), 1,
      aux_sym_filename_repeat1,
  [883] = 3,
    ACTIONS(242), 1,
      anon_sym_and,
    ACTIONS(293), 1,
      aux_sym_filename_token1,
    STATE(41), 1,
      aux_sym_filename_repeat1,
  [893] = 3,
    ACTIONS(289), 1,
      anon_sym_differ,
    ACTIONS(296), 1,
      aux_sym_filename_token1,
    STATE(26), 1,
      aux_sym_filename_repeat1,
  [903] = 1,
    ACTIONS(298), 2,
      ts_builtin_sym_end,
      aux_sym_source_token1,
  [908] = 1,
    ACTIONS(300), 2,
      ts_builtin_sym_end,
      aux_sym_source_token1,
  [913] = 1,
    ACTIONS(302), 2,
      ts_builtin_sym_end,
      aux_sym_source_token1,
  [918] = 1,
    ACTIONS(304), 2,
      ts_builtin_sym_end,
      aux_sym_source_token1,
  [923] = 1,
    ACTIONS(306), 2,
      ts_builtin_sym_end,
      aux_sym_source_token1,
  [928] = 2,
    ACTIONS(308), 1,
      anon_sym_PLUS_PLUS_PLUS,
    STATE(75), 1,
      sym_new_file,
  [935] = 1,
    ACTIONS(310), 2,
      ts_builtin_sym_end,
      aux_sym_source_token1,
  [940] = 1,
    ACTIONS(312), 2,
      ts_builtin_sym_end,
      aux_sym_source_token1,
  [945] = 2,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    ACTIONS(314), 1,
      aux_sym_source_token1,
  [952] = 1,
    ACTIONS(316), 2,
      anon_sym_from,
      anon_sym_to,
  [957] = 1,
    ACTIONS(318), 2,
      ts_builtin_sym_end,
      aux_sym_source_token1,
  [962] = 1,
    ACTIONS(320), 2,
      ts_builtin_sym_end,
      aux_sym_source_token1,
  [967] = 2,
    ACTIONS(236), 1,
      aux_sym_similarity_token1,
    STATE(66), 1,
      sym_mode,
  [974] = 2,
    ACTIONS(314), 1,
      aux_sym_source_token1,
    ACTIONS(322), 1,
      ts_builtin_sym_end,
  [981] = 1,
    ACTIONS(324), 2,
      ts_builtin_sym_end,
      aux_sym_source_token1,
  [986] = 2,
    ACTIONS(326), 1,
      aux_sym_source_token1,
    STATE(13), 1,
      aux_sym_changes_repeat1,
  [993] = 1,
    ACTIONS(328), 2,
      ts_builtin_sym_end,
      aux_sym_source_token1,
  [998] = 2,
    ACTIONS(330), 1,
      anon_sym_file,
    ACTIONS(332), 1,
      anon_sym_mode,
  [1005] = 1,
    ACTIONS(334), 2,
      ts_builtin_sym_end,
      aux_sym_source_token1,
  [1010] = 1,
    ACTIONS(336), 2,
      ts_builtin_sym_end,
      aux_sym_source_token1,
  [1015] = 2,
    ACTIONS(236), 1,
      aux_sym_similarity_token1,
    STATE(54), 1,
      sym_mode,
  [1022] = 1,
    ACTIONS(338), 2,
      ts_builtin_sym_end,
      aux_sym_source_token1,
  [1027] = 2,
    ACTIONS(308), 1,
      anon_sym_PLUS_PLUS_PLUS,
    STATE(71), 1,
      sym_new_file,
  [1034] = 1,
    ACTIONS(340), 2,
      ts_builtin_sym_end,
      aux_sym_source_token1,
  [1039] = 1,
    ACTIONS(342), 1,
      anon_sym_and,
  [1043] = 1,
    ACTIONS(344), 1,
      sym_linerange,
  [1047] = 1,
    ACTIONS(346), 1,
      sym_linerange,
  [1051] = 1,
    ACTIONS(348), 1,
      aux_sym_source_token1,
  [1055] = 1,
    ACTIONS(350), 1,
      aux_sym_source_token1,
  [1059] = 1,
    ACTIONS(352), 1,
      sym_commit,
  [1063] = 1,
    ACTIONS(354), 1,
      anon_sym_PERCENT,
  [1067] = 1,
    ACTIONS(356), 1,
      aux_sym_command_token1,
  [1071] = 1,
    ACTIONS(358), 1,
      aux_sym_source_token1,
  [1075] = 1,
    ACTIONS(360), 1,
      anon_sym_AT_AT2,
  [1079] = 1,
    ACTIONS(362), 1,
      aux_sym_source_token1,
  [1083] = 1,
    ACTIONS(364), 1,
      anon_sym_files,
  [1087] = 1,
    ACTIONS(366), 1,
      aux_sym_source_token1,
  [1091] = 1,
    ACTIONS(368), 1,
      aux_sym_source_token1,
  [1095] = 1,
    ACTIONS(370), 1,
      anon_sym_mode,
  [1099] = 1,
    ACTIONS(314), 1,
      aux_sym_source_token1,
  [1103] = 1,
    ACTIONS(227), 1,
      aux_sym_source_token1,
  [1107] = 1,
    ACTIONS(223), 1,
      aux_sym_source_token1,
  [1111] = 1,
    ACTIONS(372), 1,
      sym_commit,
  [1115] = 1,
    ACTIONS(374), 1,
      anon_sym_index2,
  [1119] = 1,
    ACTIONS(330), 1,
      anon_sym_file,
  [1123] = 1,
    ACTIONS(376), 1,
      anon_sym_DOT_DOT,
  [1127] = 1,
    ACTIONS(378), 1,
      aux_sym_similarity_token1,
  [1131] = 1,
    ACTIONS(332), 1,
      anon_sym_mode,
  [1135] = 1,
    ACTIONS(380), 1,
      aux_sym_source_token1,
  [1139] = 1,
    ACTIONS(382), 1,
      aux_sym_source_token1,
  [1143] = 1,
    ACTIONS(384), 1,
      ts_builtin_sym_end,
  [1147] = 1,
    ACTIONS(386), 1,
      anon_sym_differ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 61,
  [SMALL_STATE(6)] = 119,
  [SMALL_STATE(7)] = 177,
  [SMALL_STATE(8)] = 235,
  [SMALL_STATE(9)] = 293,
  [SMALL_STATE(10)] = 346,
  [SMALL_STATE(11)] = 385,
  [SMALL_STATE(12)] = 424,
  [SMALL_STATE(13)] = 459,
  [SMALL_STATE(14)] = 494,
  [SMALL_STATE(15)] = 524,
  [SMALL_STATE(16)] = 554,
  [SMALL_STATE(17)] = 584,
  [SMALL_STATE(18)] = 614,
  [SMALL_STATE(19)] = 644,
  [SMALL_STATE(20)] = 658,
  [SMALL_STATE(21)] = 672,
  [SMALL_STATE(22)] = 686,
  [SMALL_STATE(23)] = 700,
  [SMALL_STATE(24)] = 711,
  [SMALL_STATE(25)] = 722,
  [SMALL_STATE(26)] = 733,
  [SMALL_STATE(27)] = 743,
  [SMALL_STATE(28)] = 753,
  [SMALL_STATE(29)] = 763,
  [SMALL_STATE(30)] = 773,
  [SMALL_STATE(31)] = 783,
  [SMALL_STATE(32)] = 793,
  [SMALL_STATE(33)] = 803,
  [SMALL_STATE(34)] = 813,
  [SMALL_STATE(35)] = 823,
  [SMALL_STATE(36)] = 833,
  [SMALL_STATE(37)] = 843,
  [SMALL_STATE(38)] = 853,
  [SMALL_STATE(39)] = 863,
  [SMALL_STATE(40)] = 873,
  [SMALL_STATE(41)] = 883,
  [SMALL_STATE(42)] = 893,
  [SMALL_STATE(43)] = 903,
  [SMALL_STATE(44)] = 908,
  [SMALL_STATE(45)] = 913,
  [SMALL_STATE(46)] = 918,
  [SMALL_STATE(47)] = 923,
  [SMALL_STATE(48)] = 928,
  [SMALL_STATE(49)] = 935,
  [SMALL_STATE(50)] = 940,
  [SMALL_STATE(51)] = 945,
  [SMALL_STATE(52)] = 952,
  [SMALL_STATE(53)] = 957,
  [SMALL_STATE(54)] = 962,
  [SMALL_STATE(55)] = 967,
  [SMALL_STATE(56)] = 974,
  [SMALL_STATE(57)] = 981,
  [SMALL_STATE(58)] = 986,
  [SMALL_STATE(59)] = 993,
  [SMALL_STATE(60)] = 998,
  [SMALL_STATE(61)] = 1005,
  [SMALL_STATE(62)] = 1010,
  [SMALL_STATE(63)] = 1015,
  [SMALL_STATE(64)] = 1022,
  [SMALL_STATE(65)] = 1027,
  [SMALL_STATE(66)] = 1034,
  [SMALL_STATE(67)] = 1039,
  [SMALL_STATE(68)] = 1043,
  [SMALL_STATE(69)] = 1047,
  [SMALL_STATE(70)] = 1051,
  [SMALL_STATE(71)] = 1055,
  [SMALL_STATE(72)] = 1059,
  [SMALL_STATE(73)] = 1063,
  [SMALL_STATE(74)] = 1067,
  [SMALL_STATE(75)] = 1071,
  [SMALL_STATE(76)] = 1075,
  [SMALL_STATE(77)] = 1079,
  [SMALL_STATE(78)] = 1083,
  [SMALL_STATE(79)] = 1087,
  [SMALL_STATE(80)] = 1091,
  [SMALL_STATE(81)] = 1095,
  [SMALL_STATE(82)] = 1099,
  [SMALL_STATE(83)] = 1103,
  [SMALL_STATE(84)] = 1107,
  [SMALL_STATE(85)] = 1111,
  [SMALL_STATE(86)] = 1115,
  [SMALL_STATE(87)] = 1119,
  [SMALL_STATE(88)] = 1123,
  [SMALL_STATE(89)] = 1127,
  [SMALL_STATE(90)] = 1131,
  [SMALL_STATE(91)] = 1135,
  [SMALL_STATE(92)] = 1139,
  [SMALL_STATE(93)] = 1143,
  [SMALL_STATE(94)] = 1147,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(60),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(90),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(74),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [69] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [72] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [78] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [81] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [87] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [93] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [99] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(32),
  [102] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(30),
  [105] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [108] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hunk, 2, 0, 2),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_hunk, 2, 0, 2),
  [115] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [117] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 2, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 2, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_changes, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_changes, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_changes_repeat2, 2, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_changes_repeat2, 2, 0, 0),
  [137] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_changes_repeat2, 2, 0, 0), SHIFT_REPEAT(83),
  [140] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_changes_repeat2, 2, 0, 0), SHIFT_REPEAT(84),
  [143] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_changes_repeat2, 2, 0, 0), SHIFT_REPEAT(27),
  [146] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_changes_repeat2, 2, 0, 0), SHIFT_REPEAT(27),
  [149] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_changes_repeat2, 2, 0, 0), SHIFT_REPEAT(28),
  [152] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_changes_repeat2, 2, 0, 0), SHIFT_REPEAT(28),
  [155] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_changes_repeat2, 2, 0, 0), SHIFT_REPEAT(32),
  [158] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_changes_repeat2, 2, 0, 0), SHIFT_REPEAT(30),
  [161] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_changes_repeat2, 2, 0, 0), SHIFT_REPEAT(39),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0),
  [168] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(60),
  [171] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [174] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(90),
  [177] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [180] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(78),
  [183] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(85),
  [186] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_block_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hunks, 1, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_hunks, 1, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_hunks_repeat1, 2, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_hunks_repeat1, 2, 0, 0),
  [197] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_hunks_repeat1, 2, 0, 0), SHIFT_REPEAT(68),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_changes_repeat1, 2, 0, 0),
  [202] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_changes_repeat1, 2, 0, 0), SHIFT_REPEAT(12),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_changes_repeat1, 2, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_repeat1, 2, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_hunk, 3, 0, 3),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_hunk, 3, 0, 3),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 8, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 8, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 7, 0, 0),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 7, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_addition, 1, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_deletion, 1, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_filename_repeat1, 2, 0, 0),
  [231] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_filename_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_index, 4, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_filename, 1, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [242] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_filename_repeat1, 2, 0, 0),
  [244] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_filename_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [247] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_addition, 1, 0, 0),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [251] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_deletion, 1, 0, 0),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [255] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_context, 1, 0, 0),
  [257] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_context, 1, 0, 0),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_change, 1, 0, 0),
  [265] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_change, 1, 0, 0),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [269] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_location, 4, 0, 0),
  [271] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_location, 4, 0, 0),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [275] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 0),
  [277] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_comment, 1, 0, 0),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [283] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_special, 1, 0, 0),
  [285] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_special, 1, 0, 0),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [289] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_filename, 1, 0, 0),
  [291] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [293] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_filename_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [296] = {.entry = {.count = 1, .reusable = false}}, SHIFT(26),
  [298] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_similarity, 4, 0, 1),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_deletion, 2, 0, 0),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_index, 5, 0, 0),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_location, 5, 0, 0),
  [306] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
  [308] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [310] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_change, 6, 0, 0),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_special, 2, 0, 0),
  [314] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [316] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [318] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_change, 2, 0, 0),
  [320] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_change, 4, 0, 0),
  [322] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source, 2, 0, 0),
  [324] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_context, 2, 0, 0),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [328] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_old_file, 2, 0, 0),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [334] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_new_file, 2, 0, 0),
  [336] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_addition, 2, 0, 0),
  [338] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mode, 1, 0, 0),
  [340] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_file_change, 3, 0, 0),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [358] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [360] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [362] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [366] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [368] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [370] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [372] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [374] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [376] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [378] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [380] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 3, 0, 0),
  [382] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [384] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [386] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_diff(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "diff",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
